# Default values for mpijob.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

useHostNetwork: false
useHostPID: false
useHostIPC: false
gpuCount: 0 # user define

# rsync image
rsyncImage: registry.cn-zhangjiakou.aliyuncs.com/tensorflow-samples/rsync
# git sync image
gitImage: bootstrapper:5000/sextant/git-sync-amd64:xyd-20180828

shmSize: 2Gi
privileged: false

useTensorboard: false
tensorboardImage: registry.cn-zhangjiakou.aliyuncs.com/tensorflow-samples/tensorflow:1.5.0-devel
tensorboardImagePullpolicy: Always
tensorboardServiceType: NodePort

launcherOnMaster: false
retry: 0
